##################################################################################
### Start-Upy
##################################################################################

- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/state"
        payload: "" 
    - service: mqtt.publish
      data:
        topic: "tasmotas/cmnd/state"
        payload: "" 
        

- alias: "Homekit Start"
  trigger:
    - platform: homeassistant
      event: start
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
    - platform: event
      event_type: zwave.network_complete_some_dead
  action:
    - delay: 00:01
    - service: homekit.start

##################################################################################
###BACKUP
##################################################################################

- alias: Codzienny BackUP o 6AM
  id: codziennybackupiczyszczenie
  trigger:
    platform: time
    at: '06:00:00'
  action:
    - service: hassio.snapshot_full
      data_template:
        name: BackUP {{now().strftime('%d-%m-&Y') }}
    - service: rest_command.dobackup

##################################################################################
###POWIADOMIENIA
##################################################################################

- alias: Burza_BlitzOrtnung
  trigger:
    - platform: state
      entity_id: sensor.blitzortung_lightning_distance
      from: 'unknown'
#      to: 'on'
  action:
    service: notify.ios_iphone_sinq
    data_template:
      title: 'Wyładowania atmosferyczne bliżej niż 10km'
      data:
        message: "Wyładowania atmosferyczne bliżej niż 10km"

        
- alias: Burza_warning
  trigger:
      - platform: state
        entity_id: binary_sensor.burze_dzis_net_storm_warning
        from: 'off'
  action:
    service: notify.ios_iphone_sinq
    data_template:
      title: 'Ostrzeżenie przed burzami.'
      data:
        message: "Wydano ostrzeżenie przed burzami"   


- alias: Drzwi_wejsciowe
  trigger:
    - platform: state
      entity_id: sensor.door_entrance
#      from: 'zamknięte'
#      to: 'otwarte'
  action:
    service: notify.ios_iphone_sinq
    data_template:
      title: 'Drzwi wejściowe'
      data:
      message: "Drzwi wejściowe zostały {{ sensor.door_entrance.state }}."   
#- alias: Wysłanie wiadomości przy Alercie
#  trigger:
#    - platform: state
#      entity_id: input_boolean.test
#      from: 'off'
#      to: 'on'
#  action:
#   service: notify.notify
#   data_template:
#      title: 'Ktoś dzwoni do bramki'
#      message: >
#        "DING DONG"
#      data:
#        push:
#          category: camera
#        entity_id: camera.wejscie
